version: '3.7'

services:
  db:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: p1c4d1nh0
    ports:
      - 27017:27017

  db-admin:
    image: mongo-express
    restart: always
    ports:
        - 8081:8081
    depends_on:
        - db
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: p1c4d1nh0
        ME_CONFIG_MONGODB_SERVER: db
